version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Manu@2003
      MYSQL_DATABASE: blog_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  blog-backend:
    build: .
    container_name: blog-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/blog_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Manu@2003

volumes:
  mysql_data:
